CREATE TABLE developit_user_skills (
    user_id INTEGER
    REFERENCES developit_users(id) ON DELETE CASCADE,
    skill_name text
    REFERENCES developit_skills(skill_name) ON DELETE CASCADE NOT NULL,
    skill_level text
    REFERENCES developit_levels(skill_level) ON DELETE CASCADE NOT NULL,
     id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY   
);